name: Spotify Now Playing
on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Spotify Now Playing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README with Spotify song
        uses: kittinan/spotify-github-profile@master
        with:
          spotify_client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          spotify_client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          spotify_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          open_new_tab: 'true'
